[build]
  command = "npm run build"
  functions = "functions"
  publish = "src/.next"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  [context.production.environment]

[context.branch-deploy]