# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - restore_cache:
          keys:
            - cypress-3.5.0
      - restore_cache:
          keys:
            - global-dependency-cache-v3
      - run: apt-get --assume-yes install jq
      # - run: apt-get --assume-yes install libvips
      # - run: apt-get --assume-yes install ghostscript
      # - run: npm install node-gyp -g
      - run: npm install netlify-cli@2.12.0 -g
      - run: npm install
      - run: npm run lint
      - run: npm run test:ci
      - run: npm run export
      - run: npm run test-ua:ci
      - run: ls -la /root/.cache/

      - store_artifacts:
          path: /root/project/cypress/videos/index.js.mp4
          destination: index-ua-test-video
      - store_artifacts:
          path: /root/project/cypress/videos/anagram.js.mp4
          destination: anagram-ua-test-video
      - store_artifacts:
          path: /root/.npm/_logs/
          destination: node-logs
      - store_test_results:
            path: coverage
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: cypress-3.5.0
          paths:
            - /root/.cache/Cypress/3.5.0/Cypress/Cypress
      - save_cache:
          key: global-dependency-cache-v3
          paths:
            - /usr/local/lib/node_modules/
