# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cypress/included:3.4.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - restore_cache:
          keys:
            - cypress-3.4.1
      - restore_cache:
          keys:
            - netlify-cli-2.12.0
      - run: npm install
      - run: npm install netlify-cli@2.12.0 -g
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: cypress-3.4.1
          paths:
            - /root/.cache/Cypress
      - save_cache:
          key: netlify-cli-2.12.0
          paths:
            - /usr/local/bin/netlify
            - /usr/local/lib/node_modules/netlify-cli/bin/run
  test:
    docker:
      - image: cypress/included:3.4.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run: ls -la
      - run: npm install
      - run: npm test -- --collect-coverage
      - store_test_results:
            path: coverage

  ua-test:
    docker: 
      - image: cypress/included:3.4.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - restore_cache:
          keys:
            - netlify-cli-2.12.0
      - restore_cache:
          keys:
            - cypress-3.4.1

      - run: npm run export
      - run: apt-get --assume-yes install jq
      - run: npm install netlify-cli@2.12.0 -g
      - run: npm run test-ua:ci
      - store_artifacts:
          path: /root/project/cypress/videos/index.js.mp4
          destination: ci-video
  deploy:
    filters:
      branches:
        only:
          - master
    docker:
      - image: cypress/included:3.4.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run: npm install
      - run: npm install netlify-cli -g
      - run: npm run export
      - run: netlify deploy --prod

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - ua-test:
          requires:
            - build
      - deploy:
          requires:
            - test
            - ua-test