# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: cypress/included:3.4.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ls -la
      - run: npm install
      - run: npm test
      - store_test_results:
            path: coverage

  ua-test:
    docker: 
      - image: cypress/included:3.4.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm install netlify-cli -g
      - run: npm run export
      - run: apt-get --assume-yes install jq
      - run: npm run start > /dev/null | CYPRESS_baseUrl=$(netlify deploy --json | jq .deploy_url) cypress run
  deploy:
    docker:
      - image: cypress/included:3.4.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - run: npm run build
      - run: netlify deploy --prod

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - ua-test
      - deploy:
          requires:
            - test
            - ua-test